# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-17 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HackerNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hacker_id', models.IntegerField(db_index=True)),
                ('user_name', models.CharField(max_length=30)),
                ('article_title', models.CharField(max_length=40)),
                ('article_url', models.URLField()),
                ('article_score', models.IntegerField()),
                ('article_description', models.TextField()),
                ('sentiment', models.SmallIntegerField(choices=[(0, 'Positive'), (1, 'Negative')])),
            ],
        ),
    ]
