# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-17 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerNews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackernews',
            name='article_title',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
